# Generated by Django 2.1 on 2019-03-05 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(related_name='member', through='TM.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
