# Generated by Django 2.1 on 2019-03-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='url',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
