# Generated by Django 2.1 on 2019-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0007_auto_20190307_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.CharField(default='lolamlol', max_length=400),
            preserve_default=False,
        ),
    ]
