# Generated by Django 2.1 on 2019-03-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0012_auto_20190308_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TM.UserProfile'),
            preserve_default=False,
        ),
    ]
