# Generated by Django 2.1 on 2019-03-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0013_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptotask',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TM.Teams'),
            preserve_default=False,
        ),
    ]
