# Generated by Django 2.1 on 2019-03-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0014_membershiptotask_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unread', models.IntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TM.Comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TM.UserProfile')),
            ],
        ),
    ]
