# Generated by Django 2.1 on 2019-03-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TM', '0015_messagenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotification',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TM.Task'),
            preserve_default=False,
        ),
    ]
